"""Entrant table (Step 2). EVERBEE ESTIMATE — NOT ETSY TRANSACTION DATA.
Selection (deterministic):
  A) every job cluster except IP_RISK / REJECT_RISK / OTHER: the top 3 CLEAN shops by 12-mo units (best listing per shop)
  B) the ADHD_ADULT overlay: every CLEAN shop (best listing per shop)
  A shop appears once per table section. Listing count per shop was NOT pulled (shop lifetime sales are the size proxy;
  every entrant passed shop sales <= 15,000 and listing share of shop sales >= 5%).
Format is inferred from the title by regex (FORMAT below)."""
import json, os, re
from collections import defaultdict
H = os.path.dirname(os.path.abspath(__file__))
FORMAT = [('Notion', r'notion'), ('Google Sheets/Excel', r'google sheet|excel|spreadsheet|sheets'), ('Canva', r'canva'),
          ('Goodnotes/digital planner', r'goodnotes|notability|digital planner|ipad'), ('ChatGPT tool', r'chatgpt|\bai\b'),
          ('Printable PDF', r'printable|pdf|print')]
def fmt(t):
    for f, rx in FORMAT:
        if re.search(rx, t, re.I): return f
    return 'digital file'
def num(s):
    s = str(s).replace('$', '').replace(',', '').replace(' Mo.', '').strip()
    try: return float(s)
    except: return 0.0
def best(rows):
    by = defaultdict(list)
    for r in rows:
        if r['status'] == 'CLEAN': by[r['shop']].append(r)
    return sorted((max(v, key=lambda r: num(r['units'])) for v in by.values()), key=lambda r: -num(r['units']))
def line(r, buyer):
    return (f"| {r['shop']} | {r['shop_age']} | not pulled | {r['shop_sales']} | {r['title'][:70].replace('|', '/')} | {r['listing_id']} | "
            f"{r['listing_age']} | {r['price']} | {r['units']} | {r['revenue']} | {r['active']}/12 | {r['last3']} | {buyer} | {fmt(r['title'])} | {r['cluster']} |")
HDR = ("| Shop | Shop age | Listings | Shop sales | Product | Listing ID | Listing age | Price | 12-mo units | 12-mo revenue | Active months | Last 3 mo | Buyer / job | Format | Domain |\n"
       "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
if __name__ == '__main__':
    d = json.load(open(os.path.join(H, 'clusters.json')))
    by = defaultdict(list)
    for r in d['listings']: by[r['cluster']].append(r)
    out = ['# ENTRANT TABLE — EVERBEE ESTIMATE — NOT ETSY TRANSACTION DATA', '', '_Generated by `entrant_table.py` from `clusters.json`. Do not hand-edit._', '',
           '## A. Cross-domain sample (top 3 CLEAN shops per job cluster)', '', HDR]
    nA = set()
    for c in sorted(by):
        if c in ('IP_RISK', 'REJECT_RISK', 'OTHER'): continue
        for r in best(by[c])[:3]:
            out.append(line(r, d['clusters'][c]['buyer_job'])); nA.add(r['shop'])
    adhd_re = re.compile(r'adhd|neurodivergent|executive (dys)?function', re.I); kid = re.compile(r'kids?|toddler|child|classroom|student|teacher|visual schedule|png|clip ?art|\bstl\b|fidget', re.I)
    adhd = [r for r in d['listings'] if adhd_re.search(r['title']) and not kid.search(r['title'])]
    B = best(adhd)
    out += ['', '## B. ADHD_ADULT buyer overlay (every CLEAN shop)', '', HDR] + [line(r, 'adult with ADHD: ' + d['clusters'][r['cluster']]['buyer_job']) for r in B]
    out += ['', f'Section A distinct shops: {len(nA)} across {len([c for c in by if c not in ("IP_RISK","REJECT_RISK","OTHER")])} domains. Section B distinct CLEAN shops: {len(B)}.',
            f'Union of distinct shops: {len(nA | {r["shop"] for r in B})}.']
    open(os.path.join(H, 'ENTRANT-TABLE.md'), 'w').write('\n'.join(out) + '\n')
    print(out[-2]); print(out[-1])
